image: docker/compose:latest

services:
  - docker:19.03.1-dind

# Select what we should cache
cache:
  paths:
  - progression/vendor

stages:
  - build_image
  - test
  - deploy_image
  - build_doc
  - deploy_doc

variables:
  PROGRESSION_DIR: $CI_PROJECT_DIR
  DOCKER_TLS_CERTDIR: ""


.preparer_contexte: &preparer_contexte
    - mkdir ~/.ssh && cp $ID_RSA ~/.ssh/id_rsa
    - docker context create --docker host=ssh://$CD_USER@$CD_HOST:$CD_PORT --description="Production" prod
    - docker context use prod

.login: &login
    - apk add ca-certificates
    - DOCKER_HOST= 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    

# Stage test

# Tests unitaires
test_unitaires:
  stage: test
  needs: 
    - job: const_image
      optional: true
  environment: tests
  script:
    - docker-compose run -v $PROGRESSION_DIR/progression/app:/var/www/progression/app -v $PROGRESSION_DIR/progression/tests:/var/www/progression/tests -v $PROGRESSION_DIR/progression/phpstan.neon:/var/www/progression/phpstan.neon -v $PROGRESSION_DIR/progression/phpunit.xml:/var/www/progression/phpunit.xml tests 
  except:
    - master

# Linter
linter:
  stage: test
  needs: []
  environment: tests
  script:
    - docker-compose run -v $PROGRESSION_DIR/progression/app:/var/www/progression/app -v $PROGRESSION_DIR/progression/tests:/var/www/progression/tests lint
  except:
    - master

# Stage build_image

# Construction de l'image
const_image:
  stage: build_image
  before_script: *login
  script:
    - docker build -t $CI_REGISTRY/progression/progression_backend:test progression
  only:
    - master
    - dev

# Pousser l'image dans le dépôt distant
push_image:
  stage: build_image
  needs: [const_image]
  before_script: *login
  script:
    - docker push $CI_REGISTRY/progression/progression_backend:test
  only:
    - master
    - dev


# Stage deploy_image

# Déploiement sur /dev
deploy_dev:
  stage: deploy_image
  needs: [push_image, test_unitaires, linter]
  environment:
    name: dev
    url: https://progression.dti.crosemont.quebec/dev/
  before_script:
    - *preparer_contexte
    - *login
  script:
    - docker-compose -p dev up -d progression
  only:
    - dev

# Déploiement sur /demo
deploy_demo:
  stage: deploy_image
  needs: [push_image]
  environment:
    name: demo
    url: https://progression.dti.crosemont.quebec/demo/
  before_script:
    - *preparer_contexte
    - *login
  script:
    - docker-compose -p demo up -d progression
  only:
    - master

# Déploiement sur /pilote
deploy_pilote:
  stage: deploy_image
  needs: [push_image]
  environment:
    name: pilote
    url: https://progression.dti.crosemont.quebec/pilote/
  before_script:
    - *preparer_contexte
    - *login
  script:
    - docker-compose -p pilote up -d progression
  only:
    - master

# Déploiement sur /staging
deploy_staging:
  stage: deploy_image
  needs: [push_image]
  environment:
    name: staging
    url: https://progression.dti.crosemont.quebec/staging/
  before_script:
    - *preparer_contexte
    - *login
  script:
    - docker tag $CI_REGISTRY/progression/progression_backend:test $CI_REGISTRY/progression/progression_backend:latest   
    - docker push $CI_REGISTRY/progression/progression_backend:latest
    - docker-compose -p staging up -d progression
  only:
    - master

# Stage build_doc

# Production de la documentation dev
pages_dev:
  stage: build_doc
  needs: [deploy_dev]
  variables:
    PROGRESSION_API_URL: https://progression.dti.crosemont.quebec/dev/api/v1
  script:
  - docker run -e PROGRESSION_API_URL=$PROGRESSION_API_URL -v "$PROGRESSION_DIR/:/tmp/" $CI_REGISTRY/progression/dev:latest emacs --batch --load ~/.emacs.el --load /tmp/doc/publish.el --funcall org-publish-all
  - mkdir -p public/dev && cp -r $PROGRESSION_DIR/progression/app/html/doc/* public/dev/
  - "! grep -c nil public/dev/api.html # Vérifie que la production de l'API n'a pas produit d'erreur"
  only:
    - dev
  artifacts:
    paths:
    - public

# Production de la documentation master
pages_master:
  stage: build_doc
  needs:
    - job: deploy_staging
      optional: true
  variables:
    PROGRESSION_API_URL: https://progression.dti.crosemont.quebec/staging/api/v1
  script:
  - docker run -e PROGRESSION_API_URL=$PROGRESSION_API_URL -v "$PROGRESSION_DIR/:/tmp/" $CI_REGISTRY/progression/dev:latest emacs --batch --load ~/.emacs.el --load /tmp/doc/publish.el --funcall org-publish-all
  - mkdir public && cp -r $PROGRESSION_DIR/progression/app/html/doc/* public/
  - "! grep -c nil public/api.html # Vérifie que la production de l'API n'a pas produit d'erreur"
  only:
    - dev
    - master
  artifacts:
    paths:
    - public


# Stage deploy_doc

# Déploiement de la doc
pages:
  stage: deploy_doc
  script:
    - echo OK #apparemment nécessaire...
  artifacts:
    paths:
    - public
  only:
    - dev
    - master
