image: docker/compose:1.29.2

default:
  tags: [docker]

services:
  - docker:20.10.16-dind

# Select what we should cache
cache:
  paths:
  - progression/vendor

stages:
  - verifications
  - build_image
  - test
  - tag_image
  - deploy_image
  - build_doc
  - deploy_doc

variables:
  PROGRESSION_DIR: $CI_PROJECT_DIR
  DOCKER_TLS_CERTDIR: ""
  BRANCHE: $CI_COMMIT_REF_NAME

.preparer_contexte: &preparer_contexte
    - apk add ca-certificates openssh
    - mkdir ~/.ssh && cp $ID_RSA ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
    - echo -e "Host *\n  StrictHostKeyChecking no" > ~/.ssh/config
    - docker context create --docker host=ssh://$CD_USER@$CD_HOST:$CD_PORT --description="Production" prod
    - docker context use prod
    - DOCKER_HOST= 

.login: &login
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# Stage test

# Tests unitaires
test_unitaires:
  stage: test
  needs: 
    - job: const_image
      optional: true
  script:
    - TAG_DEPLOY=$BRANCHE docker-compose pull tests
    - TAG_DEPLOY=$BRANCHE docker-compose run -v $PROGRESSION_DIR/progression/app:/var/www/progression/app -v $PROGRESSION_DIR/progression/tests:/var/www/progression/tests -v $PROGRESSION_DIR/progression/phpstan.neon:/var/www/progression/phpstan.neon -v $PROGRESSION_DIR/progression/phpunit.xml:/var/www/progression/phpunit.xml tests 
  except:
    - master

# Linter
linter:
  stage: test
  needs: []
  script:
    - docker-compose run -v $PROGRESSION_DIR/progression/app:/var/www/progression/app -v $PROGRESSION_DIR/progression/tests:/var/www/progression/tests lint
  except:
    - master

# Stage build_image

version_check:
  stage: verifications
  script:
    - docker run -v $PWD:/progression_backend bitnami/git bash -c 'git config --global --add safe.directory /progression_backend && cd /progression_backend && dpkg --compare-versions "$(git show HEAD:VERSION|cut -d "=" -f 2)" "gt" "$(git show HEAD^:VERSION|cut -d "=" -f 2)" || ( echo ERREUR la version n’a pas avancé && exit 1 )'
  only:
  - master

# Construction de l'image
const_image:
  stage: build_image
  before_script: *login
  variables:
    DOCKER_BUILDKIT: 1 
  script:
    - docker build --cache-from $CI_REGISTRY/$CI_PROJECT_PATH:$BRANCHE --build-arg BUILDKIT_INLINE_CACHE=1 -t $CI_REGISTRY/$CI_PROJECT_PATH:$BRANCHE progression
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:$BRANCHE


# Stage tag

tag_latest:
  stage: tag_image
  needs: [const_image]
  before_script:
    - *login
  script:
    - docker pull $CI_REGISTRY/$CI_PROJECT_PATH:$BRANCHE
    - docker tag $CI_REGISTRY/$CI_PROJECT_PATH:$BRANCHE $CI_REGISTRY/$CI_PROJECT_PATH:latest   
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH:latest
  only:
    - master

    
# Stage deploy_image

# Déploiement sur /dev
deploy_dev:
  stage: deploy_image
  needs: [test_unitaires, linter]
  environment:
    name: dev
    url: https://progression.dti.crosemont.quebec/dev/api/v1/
    on_stop: stop_dev
  before_script:
    - *preparer_contexte
    - *login
  script:
    - TAG_DEPLOY=dev docker-compose pull progression
    - TAG_DEPLOY=dev docker-compose -p dev up --force-recreate --no-deps -d progression
  only:
    - dev

stop_dev:
  stage: deploy_image
  environment:
    name: dev
    action: stop
  before_script:
    - *preparer_contexte
  script:
    - docker-compose -p dev stop progression
  when:
    manual
    
# Déploiement sur /demo
deploy_demo:
  stage: deploy_image
  needs: [tag_latest]
  environment:
    name: demo
    url: https://progression.dti.crosemont.quebec/demo/api/v1/
    on_stop: stop_demo
  before_script:
    - *preparer_contexte
    - *login
  script:
    - TAG_DEPLOY=latest docker-compose pull progression
    - TAG_DEPLOY=latest docker-compose -p demo up --force-recreate --no-deps -d progression
  only:
    - master

stop_demo:
  stage: deploy_image
  environment:
    name: demo
    action: stop
  before_script:
    - *preparer_contexte
  script:
    - docker-compose -p demo stop progression
  when:
    manual

# Déploiement sur /pilote
deploy_pilote:
  stage: deploy_image
  needs: [tag_latest]
  environment:
    name: pilote
    url: https://progression.dti.crosemont.quebec/pilote/api/v1/
    on_stop: stop_pilote
  before_script:
    - *preparer_contexte
    - *login
  script:
    - TAG_DEPLOY=latest docker-compose pull progression
    - TAG_DEPLOY=latest docker-compose -p pilote up --force-recreate --no-deps -d progression
  only:
    - master

stop_pilote:
  stage: deploy_image
  environment:
    name: pilote
    action: stop
  before_script:
    - *preparer_contexte
  script:
    - docker-compose -p pilote stop progression
  when:
    manual

# Déploiement sur /staging
deploy_staging:
  stage: deploy_image
  needs: [tag_latest]
  environment:
    name: staging
    url: https://progression.dti.crosemont.quebec/staging/api/v1/
    on_stop: stop_staging
  before_script:
    - *preparer_contexte
    - *login
  script:
    - TAG_DEPLOY=latest docker-compose pull progression
    - TAG_DEPLOY=latest docker-compose -p staging up --force-recreate --no-deps -d progression
  only:
    - master

stop_staging:
  stage: deploy_image
  environment:
    name: staging
    action: stop
  before_script:
    - *preparer_contexte
  script:
    - docker-compose -p staging stop progression
  when:
    manual

# Déploiement sur progression.crosemont.qc.ca/staging
deploy_staging_2:
  stage: deploy_image
  needs: [tag_latest]
  environment:
    name: staging
    url: https://progression.crosemont.qc.ca/staging/api/v1/
    on_stop: stop_staging_2
  before_script:
    - export CD_HOST=progression.crosemont.qc.ca CD_PORT=22 CD_USER=updater
    - *preparer_contexte
    - *login
  script:
    - TAG_DEPLOY=latest docker-compose pull progression
    - TAG_DEPLOY=latest docker-compose -p staging up --force-recreate --no-deps -d progression
  only:
    - master

stop_staging_2:
  stage: deploy_image
  environment:
    name: staging
    action: stop
  before_script:
    - export CD_HOST=progression.crosemont.qc.ca CD_PORT=22 CD_USER=updater
    - *preparer_contexte
  script:
    - docker-compose -p staging stop progression
  when:
    manual


# Stage build_doc

# Production de la documentation dev
pages_dev:
  stage: build_doc
  needs: [deploy_dev]
  variables:
    PROGRESSION_API_URL: https://progression.dti.crosemont.quebec/dev/api/v1api/v1/
  script:
  - docker run -e PROGRESSION_API_URL=$PROGRESSION_API_URL -v "$PROGRESSION_DIR/:/tmp/" $CI_REGISTRY/progression/dev:latest emacs --batch --load ~/.emacs.el --load /tmp/doc/publish.el --funcall org-publish-all
  - mkdir -p public/dev && cp -r $PROGRESSION_DIR/progression/app/html/doc/* public/dev/
  - "! grep -c nil public/dev/api.html # Vérifie que la production de l'API n'a pas produit d'erreur"
  only:
    - dev
  artifacts:
    paths:
    - public

# Production de la documentation master
pages_master:
  stage: build_doc
  needs:
    - job: deploy_staging
      optional: true
  variables:
    PROGRESSION_API_URL: https://progression.dti.crosemont.quebec/staging/api/v1api/v1/
  script:
  - docker run -e PROGRESSION_API_URL=$PROGRESSION_API_URL -v "$PROGRESSION_DIR/:/tmp/" $CI_REGISTRY/progression/dev:latest emacs --batch --load ~/.emacs.el --load /tmp/doc/publish.el --funcall org-publish-all
  - mkdir public && cp -r $PROGRESSION_DIR/progression/app/html/doc/* public/
  - "! grep -c nil public/api.html # Vérifie que la production de l'API n'a pas produit d'erreur"
  only:
    - dev
    - master
  artifacts:
    paths:
    - public


# Stage deploy_doc

# Déploiement de la doc
pages:
  stage: deploy_doc
  script:
    - echo OK #apparemment nécessaire...
  artifacts:
    paths:
    - public
  only:
    - dev
    - master
