# Select image from https://hub.docker.com/_/php/
image: git.dti.crosemont.quebec:5050/progression/progression_backend:latest 

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
# Install all project dependencies
- php /composer.phar install --dev -d progression/

services:
  - mariadb:latest

stages:
  - test
  - doc
  - deploy

variables:
  MYSQL_DATABASE: $DB_DBNAME
  MYSQL_USER: $DB_USERNAME
  MYSQL_PASSWORD: $DB_PASSWORD
  MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
  JWT_SECRET: "secret_à_changer"
  JWT_TTL: 8640000
  AUTH_TYPE: "no"
  HTTP_ORIGIN: "https://example.com"

# We test PHP7
test_unitaires:
  stage: test
  script:
  - db/build_db.sh && mysql --default-character-set=utf8 -h $DB_SERVERNAME -uroot -p$DB_PASSWORD $DB_DBNAME < progression/tests/données_de_test.sql
  - progression/vendor/bin/phpunit --configuration progression/phpunit.xml --coverage-text
  except:
  - documentation

analyse_statique:
  stage: test
  script:
  - php -d memory_limit=1G progression/vendor/bin/phpstan analyse -c progression/phpstan.neon
  except:
  - documentation

linter:
  stage: test
  script:
  - shopt -s globstar && prettier -c progression/app/**/*.php progression/tests/**/*.php
  except:
  - documentation

# Production de la documentation
pages:
  script:
  - db/build_db.sh && mysql -h $DB_SERVERNAME -uroot -p$DB_PASSWORD $DB_DBNAME < progression/tests/données_de_test.sql
  - emacs --batch --load $HOME/.emacs.el --load doc/publish.el --funcall org-publish-all && mkdir public && cp -r progression/app/html/doc/* public/
  - bash -c "[ ! grep -q nil public/api.html ]" # Vérifie que la production de l'API n'a pas produit d'erreur
  artifacts:
    paths:
    - public
  stage: doc
  only:
  - master
  - documentation

deploy_dev:
  stage: deploy
  script:
    - chmod 400 /builds/progression/progression_backend.tmp/ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $CD_USER@$CD_HOST -p $CD_PORT $CD_COMMAND_DEV
  only:
    - dev

deploy_master:
  stage: deploy
  script:
    - chmod 400 /builds/progression/progression_backend.tmp/ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $CD_USER@$CD_HOST -p $CD_PORT $CD_COMMAND
  only:
    - master