# Select image from https://hub.docker.com/_/php/
image: php:7

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git emacs elpa-htmlize unzip python -yqq

# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- php composer.phar install --dev -d progression/

# We test PHP7
test:
  script:
  - progression/vendor/bin/phpunit --configuration progression/phpunit.xml --coverage-text
  except:
  - master
  - documentation

# Production de la documentation
.doc: &doc
  script:
  - emacs --batch --no-init-file --load doc/publish.el --funcall org-publish-all && mkdir public && cp -r progression/app/html/doc/* public/
  artifacts:
    paths:
    - public

pages:
  <<: *doc
  only:
  - dev
  - documentation


