version: "3"
services:

  db:
    build: db/ 
    container_name: progression_db
    networks:
      progressionnet:
        ipv4_address: 172.20.0.2
    volumes:
      - "./db/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always

  progression:
    image: progression_backend_progression
    build: progression/
    container_name: progression
    networks:
      progressionnet:
        ipv4_address: 172.20.0.3
    ports: 
      - 80:80
    #En développement, monte les source directement dans le conteneur
    volumes:
      - "./progression/app/progression/:/var/www/progression/app/progression"
    extra_hosts:
      - "watson.dept-info.crosemont.quebec:205.237.24.200"
    restart: always
    depends_on: 
      - db

  importeur:
    build: importeur/
    networks:
      progressionnet:
        ipv4_address: 172.20.0.4
    restart: "no"
    depends_on:
      - db
    environment:
      SOURCE: https://git.dti.crosemont.quebec/progression/progression_contenu_demo.git
      DESTINATION: mysql://quiz:password@172.20.0.2/quiz

  tests:
    image: progression_backend_progression
    build: progression/
    container_name: progression_tests
    volumes:
      - "./progression/app/:/var/www/progression/app/"
      - "./progression/tests/:/var/www/progression/tests/"
      - "./progression/phpunit.xml:/var/www/progression/phpunit.xml"
    restart: "no"
    command: /var/www/progression/vendor/bin/phpunit --configuration /var/www/progression/phpunit.xml --coverage-text

  doc:
    image: git.dti.crosemont.quebec:5050/progression/progression_backend:latest 
    volumes:
      - "./progression/app/:/progression/app/"
      - "./doc/:/doc/"
    command: emacs --batch --load /root/.emacs.el --load /doc/publish.el --funcall org-publish-all


networks:
  progressionnet:
    ipam:
      config:
        - subnet: 172.20.0.0/24
